site_name: NMaaS Documentation
nav:
  - Home: index.md
  - What is NMaaS?: 'what-is-nmaas.md'
  - Managed NMaaS:
    - Introduction: 'managed-nmaas/introduction.md'
    - NMaaS Instances: 'managed-nmaas/nmaas-instances.md'
  - Self-Hosted NMaaS:
    - Introduction: 'self-hosted-nmaas/introduction.md'
    - Quick Start: 'self-hosted-nmaas/quick-start.md'
    - Production Installation Guide: 'self-hosted-nmaas/install-guide.md'
    - Local Development Environment: 'self-hosted-nmaas/local-vm.md'
  - NMaaS Applications:
    - List of Supported Applications: 'nmaas-applications/application-list.md'
    - Adding a new Application: 'nmaas-applications/new-application.md'
    - Application Deployment Tutorials:
      - LibreNMS: 'nmaas-applications/tutorials/librenms.md'
      - Booked: 'nmaas-applications/tutorials/booked.md'
      - Uptime Kuma: 'nmaas-applications/tutorials/uptime-kuma.md'
  - Blog:
    - NMaaS-101 - "Hello NMaaS !": 'blog/blog1/nmaas-101-1.md'
    - NMaaS-101 - "I can help! But... Please could you open these two doors?": 'blog/blog2/nmaas-101-2.md'
  - Contact: contact.md
  - About: about.md

theme:
  logo: 'img/NMaaS-logo-transparent-white.png'
  favicon: 'img/favicon.ico'
  name: 'material'
  palette:
    scheme: default
    primary: 'black'
    accent: 'light-blue'

extra_css:
  - 'css/extra.css'

copyright: >
  <a href="#__consent">Change cookie settings</a>

extra:
  generator: false
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'
  analytics:
    provider: google
    property: G-ZXZHTYVKN9
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - pymdownx.snippets:
        base_path: ['docs/guides/reference/snippets','.']
        check_paths: true
  - pymdownx.highlight:
        linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: false
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - attr_list
  - md_in_html